//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_GazeteUyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giris
    {
        public int Id { get; set; }
        public string Eposta { get; set; }
        public string Parola { get; set; }
        public bool Adminmi { get; set; }
    }
}
