//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_GazeteUyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int Id { get; set; }
        public string Eposta { get; set; }
        public string AdSoyad { get; set; }
        public string Parola { get; set; }
        public string ParolaTekrar { get; set; }
        public int Telefon { get; set; }
        public bool Abonelik { get; set; }
        public Nullable<System.DateTime> AboneTarih { get; set; }
        public Nullable<System.DateTime> abonelikBitis { get; set; }
        public Nullable<bool> Uyelik { get; set; }
        public string activationkey { get; set; }
    }
}
