//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_GazeteUyg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dbo_egazeteEntities : DbContext
    {
        public Dbo_egazeteEntities()
            : base("name=Dbo_egazeteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gazete> Gazete { get; set; }
        public virtual DbSet<GazeteEk> GazeteEk { get; set; }
        public virtual DbSet<Giris> Giris { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Kayit> Kayit { get; set; }
    }
}
